version: "3.9"

services:
   graph-db:
      image: "neo4j:4.4.9"
      ports:
         - "7474:7474"
         - "7687:7687"
      environment:
         NEO4J_AUTH: "neo4j/default"
         NEO4J_dbms_memory_pagecache_size: "512M"
         NEO4J_dbms_logs_debug_level: "DEBUG"
         NEO4JLABS_PLUGINS: '["apoc"]'
      volumes:
         - graphdbdata:/data
         - graphdblogs:/logs
      restart: on-failure
   social-media-api:
      build:
         context: .
      ports:
         - "7064:7064"
         - "5064:5064"
      environment:
         ASPNETCORE_ENVIRONMENT: "Production"
         GraphDatabaseSettings__UseDataSeeding: "true"
         GraphDatabaseSettings__BoltEndpoint: "bolt://graph-db:7687"
         ASPNETCORE_HTTPS_PORT: "7064"
         ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD: "mypass123"
         ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH: "/https/aspnetapp.pfx"
         ASPNETCORE_URLS: "http://+:5064;https://+:7064"
         AzureBlobStorageSettings__AccountName: "sharebookmedia"
         AzureBlobStorageSettings__EndpointSuffix: "core.windows.net"
         AzureBlobStorageSettings__AccountKey: "ErYIRbGvZZRhUnbkr0je78rD1W4bmHJz60PwGOcfQTl29lH+ITj1cPp/Of6f6Fsy6sMMO9OHtd/W+AStiQseIg=="
         GraphDatabaseSettings__DefaultDatabase: "neo4j"
         GraphDatabaseSettings__Username: "neo4j"
         GraphDatabaseSettings__Password: "default"
      restart: on-failure
      depends_on:
         - graph-db
      volumes:
         - "${USERPROFILE}\\.aspnet\\https:/https"
volumes:
   graphdbdata:
   graphdblogs:
